root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./dist/network-shaper"
  cmd = "go build -o ./dist/network-shaper ./cmd/network-shaper"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "codegen"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go", "_tcogen.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "templ", "html", "css", "js"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["go generate"]
  rerun = false
  rerun_delay = 250
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
