// Code generated by templ-component-opts; DO NOT EDIT.
// This file contains functions and methods for use with Opts in templ components.
package floatslider

import "strconv"

type Opt func(*Opts)

func DefaultOpts() *Opts {
	out := &Opts{Unit: "ms", Min: 0.0, Max: 100.0, Step: 0.1}
	return out
}
func With(opts ...Opt) *Opts {
	out := DefaultOpts()
	out.With(opts...)
	return out
}
func (o *Opts) With(opts ...Opt) *Opts {
	for _, opt := range opts {
		opt(o)
	}
	return o
}

func Label(in string) Opt {
	return func(opts *Opts) {
		opts.Label = in
	}
}

func Descr(in string) Opt {
	return func(opts *Opts) {
		opts.Descr = in
	}
}

func Unit(in string) Opt {
	return func(opts *Opts) {
		opts.Unit = in
	}
}

func Optional(in bool) Opt {
	return func(opts *Opts) {
		opts.Optional = in
	}
}

func (o *Opts) OptionalStr() string {
	return strconv.FormatBool(o.Optional)
}

func Disabled(in bool) Opt {
	return func(opts *Opts) {
		opts.Disabled = in
	}
}

func (o *Opts) DisabledStr() string {
	return strconv.FormatBool(o.Disabled)
}

func Min(in float64) Opt {
	return func(opts *Opts) {
		opts.Min = in
	}
}

func (o *Opts) MinStr() string {
	return strconv.FormatFloat(o.Min, 'f', 1, 64)
}

func Max(in float64) Opt {
	return func(opts *Opts) {
		opts.Max = in
	}
}

func (o *Opts) MaxStr() string {
	return strconv.FormatFloat(o.Max, 'f', 1, 64)
}

func Step(in float64) Opt {
	return func(opts *Opts) {
		opts.Step = in
	}
}

func (o *Opts) StepStr() string {
	return strconv.FormatFloat(o.Step, 'f', 1, 64)
}

func Value(in float64) Opt {
	return func(opts *Opts) {
		opts.Value = in
	}
}

func (o *Opts) ValueStr() string {
	return strconv.FormatFloat(o.Value, 'f', 1, 64)
}
